In [1]:
import pandas as pd
import numpy as np

In [2]:
## part a:

In [3]:
colnames=['Number of times pregnant.', 'Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'
          , 'Diastolic blood pressure (mm Hg).', 'Triceps skinfold thickness (mm).'
          , '2-Hour serum insulin (mu U/ml).', 'Body mass index (weight in kg/(height in m)^2).'
          , 'Diabetes pedigree function.', 'Age (years).', 'Class variable (0 or 1).'] 

In [4]:
df = pd.read_csv('Desktop/Diabetes.csv', names=colnames, header=None)
df

Number of times pregnant.  \
0                            6   
1                            1   
2                            8   
3                            1   
4                            0   
..                         ...   
763                         10   
764                          2   
765                          5   
766                          1   
767                          1   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test.  \
0                                                  148                           
1                                                   85                           
2                                                  183                           
3                                                   89                           
4                                                  137                           
..                                                 ...                           
763                                                101                           
764                                                122                           
765                                                121                           
766                                                126                           
767                                                 93                           

     Diastolic blood pressure (mm Hg).  Triceps skinfold thickness (mm).  \
0                                   72                                35   
1                                   66                                29   
2                                   64                                 0   
3                                   66                                23   
4                                   40                                35   
..                                 ...                               ...   
763                                 76                                48   
764                                 70                                27   
765                                 72                                23   
766                                 60                                 0   
767                                 70                                31   

     2-Hour serum insulin (mu U/ml).  \
0                                  0   
1                                  0   
2                                  0   
3                                 94   
4                                168   
..                               ...   
763                              180   
764                                0   
765                              112   
766                                0   
767                                0   

     Body mass index (weight in kg/(height in m)^2).  \
0                                               33.6   
1                                               26.6   
2                                               23.3   
3                                               28.1   
4                                               43.1   
..                                               ...   
763                                             32.9   
764                                             36.8   
765                                             26.2   
766                                             30.1   
767                                             30.4   

     Diabetes pedigree function.  Age (years).  Class variable (0 or 1).  
0                          0.627            50                         1  
1                          0.351            31                         0  
2                          0.672            32                         1  
3                          0.167            21                         0  
4                          2.288            33                         1  
..                           ...           ...                       ...  
763                

In [5]:
## part b:

In [6]:
## checking missing values and outliers:

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                                                                     Non-Null Count  Dtype  
---  ------                                                                     --------------  -----  
 0   Number of times pregnant.                                                  768 non-null    int64  
 1   Plasma glucose concentration a 2 hours in an oral glucose tolerance test.  768 non-null    int64  
 2   Diastolic blood pressure (mm Hg).                                          768 non-null    int64  
 3   Triceps skinfold thickness (mm).                                           768 non-null    int64  
 4   2-Hour serum insulin (mu U/ml).                                            768 non-null    int64  
 5   Body mass index (weight in kg/(height in m)^2).                            768 non-null    float64
 6   Diabetes pedigree function.                                

In [8]:
def minMax(df):
    return pd.Series(index=['min','max'],data=[df.min(),df.max()])
df.apply(minMax)

Number of times pregnant.  \
min                          0   
max                         17   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test.  \
min                                                  0                           
max                                                199                           

     Diastolic blood pressure (mm Hg).  Triceps skinfold thickness (mm).  \
min                                  0                                 0   
max                                122                                99   

     2-Hour serum insulin (mu U/ml).  \
min                                0   
max                              846   

     Body mass index (weight in kg/(height in m)^2).  \
min                                              0.0   
max                                             67.1   

     Diabetes pedigree function.  Age (years).  Class variable (0 or 1).  
min                        0.078            21                         0  
max                        2.420            81                         1

In [9]:
df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'] = df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'].replace((0),np.NaN)
df['Diastolic blood pressure (mm Hg).'] = df['Diastolic blood pressure (mm Hg).'].replace((0),np.NaN)
df['Triceps skinfold thickness (mm).'] = df['Triceps skinfold thickness (mm).'].replace((0),np.NaN)
df['2-Hour serum insulin (mu U/ml).'] = df['2-Hour serum insulin (mu U/ml).'].replace((0),np.NaN)
df['Body mass index (weight in kg/(height in m)^2).'] = df['Body mass index (weight in kg/(height in m)^2).'].replace((0),np.NaN)

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
mean_imput = SimpleImputer(missing_values=np.NaN, strategy='mean')

In [12]:
df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'] = mean_imput.fit_transform(df['Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'].values.reshape(-1,1))[:,0]
df['Diastolic blood pressure (mm Hg).'] = df['Diastolic blood pressure (mm Hg).'] = mean_imput.fit_transform(df['Diastolic blood pressure (mm Hg).'].values.reshape(-1,1))[:,0]
df['Triceps skinfold thickness (mm).'] = mean_imput.fit_transform(df['Triceps skinfold thickness (mm).'].values.reshape(-1,1))[:,0]
df['2-Hour serum insulin (mu U/ml).'] = mean_imput.fit_transform(df['2-Hour serum insulin (mu U/ml).'].values.reshape(-1,1))[:,0]
df['Body mass index (weight in kg/(height in m)^2).'] = mean_imput.fit_transform(df['Body mass index (weight in kg/(height in m)^2).'].values.reshape(-1,1))[:,0]

In [13]:
def minMax(df):
    return pd.Series(index=['min','max'],data=[df.min(),df.max()])
df.apply(minMax)

Number of times pregnant.  \
min                          0   
max                         17   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test.  \
min                                               44.0                           
max                                              199.0                           

     Diastolic blood pressure (mm Hg).  Triceps skinfold thickness (mm).  \
min                               24.0                               7.0   
max                              122.0                              99.0   

     2-Hour serum insulin (mu U/ml).  \
min                             14.0   
max                            846.0   

     Body mass index (weight in kg/(height in m)^2).  \
min                                             18.2   
max                                             67.1   

     Diabetes pedigree function.  Age (years).  Class variable (0 or 1).  
min                        0.078            21                         0  
max                        2.420            81                         1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                                                                     Non-Null Count  Dtype  
---  ------                                                                     --------------  -----  
 0   Number of times pregnant.                                                  768 non-null    int64  
 1   Plasma glucose concentration a 2 hours in an oral glucose tolerance test.  768 non-null    float64
 2   Diastolic blood pressure (mm Hg).                                          768 non-null    float64
 3   Triceps skinfold thickness (mm).                                           768 non-null    float64
 4   2-Hour serum insulin (mu U/ml).                                            768 non-null    float64
 5   Body mass index (weight in kg/(height in m)^2).                            768 non-null    float64
 6   Diabetes pedigree function.                                

In [15]:
## normalizing integer values:

In [16]:
from sklearn import preprocessing

In [17]:
df_scaleN = preprocessing.normalize(df[['Number of times pregnant.', 'Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'
                                        , 'Diastolic blood pressure (mm Hg).', 'Triceps skinfold thickness (mm).'
                                        , '2-Hour serum insulin (mu U/ml).', 'Body mass index (weight in kg/(height in m)^2).'
                                        , 'Diabetes pedigree function.', 'Age (years).']])
df_scaleN = pd.DataFrame(df_scaleN);
df_scaleN['Class variable (0 or 1).'] = df['Class variable (0 or 1).']
df_scaleN.columns = ['Number of times pregnant.', 'Plasma glucose concentration a 2 hours in an oral glucose tolerance test.'
                     , 'Diastolic blood pressure (mm Hg).', 'Triceps skinfold thickness (mm).'
                     , '2-Hour serum insulin (mu U/ml).', 'Body mass index (weight in kg/(height in m)^2).'
                     , 'Diabetes pedigree function.', 'Age (years).', 'Class variable (0 or 1).'] 
df_scaleN

Number of times pregnant.  \
0                     0.025315   
1                     0.005111   
2                     0.031558   
3                     0.006612   
4                     0.000000   
..                         ...   
763                   0.042321   
764                   0.009245   
765                   0.026915   
766                   0.004582   
767                   0.004990   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test.  \
0                                             0.624447                           
1                                             0.434404                           
2                                             0.721898                           
3                                             0.588467                           
4                                             0.596386                           
..                                                 ...                           
763                                           0.427443                           
764                                           0.563972                           
765                                           0.651352                           
766                                           0.577294                           
767                                           0.464076                           

     Diastolic blood pressure (mm Hg).  Triceps skinfold thickness (mm).  \
0                             0.303785                          0.147673   
1                             0.337302                          0.148208   
2                             0.252467                          0.115004   
3                             0.436392                          0.152076   
4                             0.174127                          0.152361   
..                                 ...                               ...   
763                           0.321640                          0.203141   
764                           0.323590                          0.124813   
765                           0.387582                          0.123811   
766                           0.274902                          0.133572   
767                           0.349304                          0.154692   

     2-Hour serum insulin (mu U/ml).  \
0                           0.656295   
1                           0.794950   
2                           0.613606   
3                           0.621527   
4                           0.731335   
..                               ...   
763                         0.761779   
764                         0.719056   
765                         0.602905   
766                         0.712675   
767                         0.776195   

     Body mass index (weight in kg/(height in m)^2).  \
0                                           0.141766   
1                                           0.135943   
2                                           0.091914   
3                                           0.185797   
4                                           0.187622   
..                                               ...   
763                                         0.139236   
764                                         0.170116   
765                                         0.141037   
766                                         0.137909   
767                                         0.151698   

     Diabetes pedigree function.  Age (years).  Class variable (0 or 1).  
0                       0.002645      0.210962                         1  
1                       0.001794      0.158430                         0  
2                       0.002651      0.126233                         1  
3                       0.001104      0.138852                         0  
4                       0.009960      0.143655                         1  
..                           ...           ...                       ...  
763                

In [18]:
## part c:

In [19]:
y = df_scaleN['Class variable (0 or 1).']

In [20]:
x = df_scaleN.drop(['Class variable (0 or 1).'], axis=1)

In [21]:
## part d:

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [24]:
y_train.value_counts()

0    391
1    223
Name: Class variable (0 or 1)., dtype: int64

In [25]:
y_test.value_counts()

0    109
1     45
Name: Class variable (0 or 1)., dtype: int64

In [26]:
## part e:

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
model = RandomForestClassifier(criterion="entropy", max_depth=3).fit(x_train, y_train)

In [34]:
## part f:

In [35]:
y_pred = model.predict(x_test)

In [36]:
from sklearn.metrics import classification_report, confusion_matrix

In [37]:
print(confusion_matrix(y_test, y_pred))

[[101   8]
 [ 37   8]]


In [38]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.93      0.82       109
           1       0.50      0.18      0.26        45

    accuracy                           0.71       154
   macro avg       0.62      0.55      0.54       154
weighted avg       0.66      0.71      0.66       154



In [39]:
## part g:

In [40]:
## max_depth=2

In [41]:
model1 = RandomForestClassifier(criterion="entropy", max_depth=2).fit(x_train, y_train)

In [43]:
y_pred1 = model1.predict(x_test)

In [44]:
print(confusion_matrix(y_test, y_pred1))

[[109   0]
 [ 45   0]]


In [62]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83       109
           1       0.00      0.00      0.00        45

    accuracy                           0.71       154
   macro avg       0.35      0.50      0.41       154
weighted avg       0.50      0.71      0.59       154



C:\Users\Marzieh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Marzieh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Marzieh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
## max_depth=1

In [46]:
model2 = RandomForestClassifier(criterion="entropy", max_depth=1).fit(x_train, y_train)

In [47]:
y_pred2 = model2.predict(x_test)

In [48]:
print(confusion_matrix(y_test, y_pred2))

[[109   0]
 [ 45   0]]


In [63]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83       109
           1       0.00      0.00      0.00        45

    accuracy                           0.71       154
   macro avg       0.35      0.50      0.41       154
weighted avg       0.50      0.71      0.59       154



C:\Users\Marzieh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Marzieh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Marzieh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
## max_depth=4

In [51]:
model3 = RandomForestClassifier(criterion="entropy", max_depth=4).fit(x_train, y_train)

In [52]:
y_pred3 = model3.predict(x_test)

In [53]:
print(confusion_matrix(y_test, y_pred3))

[[98 11]
 [33 12]]


In [65]:
print(classification_report(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.75      0.90      0.82       109
           1       0.52      0.27      0.35        45

    accuracy                           0.71       154
   macro avg       0.63      0.58      0.58       154
weighted avg       0.68      0.71      0.68       154



In [54]:
## max_depth=5

In [55]:
model4 = RandomForestClassifier(criterion="entropy", max_depth=5).fit(x_train, y_train)

In [56]:
y_pred4 = model4.predict(x_test)

In [57]:
print(confusion_matrix(y_test, y_pred4))

[[95 14]
 [30 15]]


In [66]:
print(classification_report(y_test, y_pred4))

              precision    recall  f1-score   support

           0       0.76      0.87      0.81       109
           1       0.52      0.33      0.41        45

    accuracy                           0.71       154
   macro avg       0.64      0.60      0.61       154
weighted avg       0.69      0.71      0.69       154



In [58]:
## max_depth=6

In [59]:
model5 = RandomForestClassifier(criterion="entropy", max_depth=6).fit(x_train, y_train)

In [60]:
y_pred5 = model5.predict(x_test)

In [61]:
print(confusion_matrix(y_test, y_pred5))

[[94 15]
 [29 16]]


In [68]:
print(classification_report(y_test, y_pred5))

              precision    recall  f1-score   support

           0       0.76      0.86      0.81       109
           1       0.52      0.36      0.42        45

    accuracy                           0.71       154
   macro avg       0.64      0.61      0.62       154
weighted avg       0.69      0.71      0.70       154



In [69]:
## max_depth=7

In [70]:
model6 = RandomForestClassifier(criterion="entropy", max_depth=7).fit(x_train, y_train)

In [71]:
y_pred6 = model6.predict(x_test)

In [72]:
print(confusion_matrix(y_test, y_pred6))

[[94 15]
 [27 18]]


In [73]:
print(classification_report(y_test, y_pred6))

              precision    recall  f1-score   support

           0       0.78      0.86      0.82       109
           1       0.55      0.40      0.46        45

    accuracy                           0.73       154
   macro avg       0.66      0.63      0.64       154
weighted avg       0.71      0.73      0.71       154



In [74]:
## max_depth=10

In [75]:
model7 = RandomForestClassifier(criterion="entropy", max_depth=10).fit(x_train, y_train)

In [76]:
y_pred7 = model7.predict(x_test)

In [77]:
print(confusion_matrix(y_test, y_pred7))

[[93 16]
 [26 19]]


In [78]:
print(classification_report(y_test, y_pred7))

              precision    recall  f1-score   support

           0       0.78      0.85      0.82       109
           1       0.54      0.42      0.48        45

    accuracy                           0.73       154
   macro avg       0.66      0.64      0.65       154
weighted avg       0.71      0.73      0.72       154



In [113]:
## max_depth=11

In [122]:
model8 = RandomForestClassifier(criterion="entropy", max_depth=11).fit(x_train, y_train)

In [123]:
y_pred8 = model8.predict(x_test)

In [124]:
print(confusion_matrix(y_test, y_pred8))

[[93 16]
 [25 20]]


In [125]:
print(classification_report(y_test, y_pred8))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82       109
           1       0.56      0.44      0.49        45

    accuracy                           0.73       154
   macro avg       0.67      0.65      0.66       154
weighted avg       0.72      0.73      0.72       154



In [126]:
## max_depth=12

In [139]:
model9 = RandomForestClassifier(criterion="entropy", max_depth=12).fit(x_train, y_train)

In [140]:
y_pred9 = model9.predict(x_test)

In [141]:
print(confusion_matrix(y_test, y_pred9))

[[95 14]
 [26 19]]


In [142]:
print(classification_report(y_test, y_pred9))

              precision    recall  f1-score   support

           0       0.79      0.87      0.83       109
           1       0.58      0.42      0.49        45

    accuracy                           0.74       154
   macro avg       0.68      0.65      0.66       154
weighted avg       0.72      0.74      0.73       154



In [177]:
## max_depth=13

In [178]:
model10 = RandomForestClassifier(criterion="entropy", max_depth=13).fit(x_train, y_train)

In [179]:
y_pred10 = model10.predict(x_test)

In [180]:
print(confusion_matrix(y_test, y_pred10))

[[93 16]
 [27 18]]


In [181]:
print(classification_report(y_test, y_pred10))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81       109
           1       0.53      0.40      0.46        45

    accuracy                           0.72       154
   macro avg       0.65      0.63      0.63       154
weighted avg       0.70      0.72      0.71       154



In [182]:
## max_depth=16

In [183]:
model11 = RandomForestClassifier(criterion="entropy", max_depth=16).fit(x_train, y_train)

In [184]:
y_pred11 = model11.predict(x_test)

In [185]:
print(confusion_matrix(y_test, y_pred11))

[[94 15]
 [25 20]]


In [186]:
print(classification_report(y_test, y_pred11))

              precision    recall  f1-score   support

           0       0.79      0.86      0.82       109
           1       0.57      0.44      0.50        45

    accuracy                           0.74       154
   macro avg       0.68      0.65      0.66       154
weighted avg       0.73      0.74      0.73       154

